services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - micro-net

  api:
    build: ./api
    container_name: node_api
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: ${DB_HOST}  # IMPORTANTE: Usamos el nombre del servicio, no localhost
      DB_USER: ${POSTGRES_DB_USER}
      DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      DB_NAME: ${POSTGRES_DB_NAME}

      API_PORT: ${PORT}
    depends_on:
      - db
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge

volumes:
  pgdata:
