version: "3.9"

services:
  api:
    build: .
    container_name: proyecto-container
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: proyecto
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - micro-net

  db:
    image: postgres:16
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: proyecto
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - micro-net

networks:
  micro-net:

volumes:
  pgdata: