version: '3.8'

services:
  # 1. Nuestro servicio de Base de Datos
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: tododb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - micro-net

  # 2. Nuestro servicio de API
  api:
    build: ./api # Le dice a Docker que busque el Dockerfile en la carpeta api/
    container_name: node_api
    ports:
      - '3000:3000'
    environment:
      # ¡Aquí está la magia! El host es el nombre del servicio de arriba ("db")
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: secretpassword
      DB_NAME: tododb
      PORT: 3000
    depends_on:
      - db # Le dice que espere a que la BD inicie primero
    networks:
      - micro-net

# 3. Declaramos la red privada que pide el taller
networks:
  micro-net:

# 4. Declaramos el volumen para que no se borren tus datos si apagas el contenedor
volumes:
  pgdata:
