version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: semana4-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - micro-net

  api:
    build:
      context: .
      dockerfile: DockerFile
    container_name: semana4-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: appuser
      DB_PASSWORD: secretpassword
      DB_NAME: appdb
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge

volumes:
  pgdata:
    driver: local
