FROM node:18-alpine AS builder

WORKDIR /app

# Copiamos solo package.json para aprovechar la cache de Docker
COPY api/package.json .
RUN npm install

# Código de la API e interfaz web
COPY server.js .
COPY public/ ./public/

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/ .

EXPOSE 3000

CMD ["npm", "start"]