services:
  db:
    image: postgres:15-alpine
    container_name: db-service
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - micro-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    container_name: api-service
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      PORT: ${PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge

volumes:
  pgdata:
